apiVersion: v1
kind: PersistentVolume
metadata:
  name: fossflow-volume
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume1/fossflow
    server: nas.batcave.local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fossflow-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fossflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fossflow
  template:
    metadata:
      labels:
        app: fossflow
    spec:
      containers:
        - name: fossflow
          image: stnsmith/fossflow:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: "production"
            - name: ENABLE_SERVER_STORAGE
              value: "true"      
            - name: STORAGE_PATH
              value: /data/diagrams
            - name: ENABLE_GIT_BACKUP
              value: "false"      
          volumeMounts:
            - name: fossflow-volume
              mountPath: /data/diagrams
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: fossflow-volume
          persistentVolumeClaim:
            claimName: fossflow-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: fossflow-service
spec:
  selector:
    app: fossflow
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
