---
- name: Gather and print all facts for servers
  hosts: homelab
  become: true
  vars_files:
    - vault2.yml

  tasks:
    - name: Test connection
      ansible.builtin.ping:

    - name: Gather distribution facts
      ansible.builtin.setup:
        filter: ansible_distribution

    - name: Print distribution details
      ansible.builtin.debug:
        msg: "Distribution is: {{ ansible_distribution }}"
...