---
- name: Gather and print all facts for servers
  hosts: homelab:k8s
  become: true
  vars_files:
    - vault2.yml

  tasks:
    - name: Test connection
      ansible.builtin.ping:

    - name: Gather all facts
      ansible.builtin.setup:

    - name: Print all gathered facts
      ansible.builtin.debug:
        var: ansible_facts
...