---
- name: Install VS Code
  hosts: homelab:k8s
  become: true
  vars_files:
    - vault2.yml

  tasks:
    - name: Ping the host
      ansible.builtin.ping:
      register: ping_result
      ignore_unreachable: true
      ignore_errors: true

    - name: Display debug info for host
      ansible.builtin.debug:
        msg: "Host {{ inventory_hostname }} is running {{ ansible_distribution }}"
      when: ping_result is not failed

    - name: Ensure required dependency is installed
      ansible.builtin.apt:
        name: libasound2
        state: latest

    - name: Detect system architecture
      ansible.builtin.command: dpkg --print-architecture
      register: system_arch
      changed_when: false

    - name: Set VS Code download URL based on architecture
      ansible.builtin.set_fact:
        vscode_url: >-
          {{
            'https://software.labjunkie.org/code_arm64.deb'
            if 'arm64' in system_arch.stdout else
            'https://software.labjunkie.org/code_amd64.deb'
          }}

    - name: Download the correct VS Code package
      ansible.builtin.get_url:
        url: "{{ vscode_url }}"
        dest: /tmp/code.deb
        mode: '0644'

    - name: Install VS Code
      ansible.builtin.apt:
        deb: /tmp/code.deb
        state: present

    - name: Cleanup VS Code .deb package
      ansible.builtin.file:
        path: /tmp/code.deb
        state: absent