---
- name: Install k8s and init cluster
  hosts: homelab:k8s
  become: true
  vars_files:
    - vault2.yml

  tasks:
    - name: Ensure curl is installed
      ansible.builtin.package:
        name: curl
        state: present

    - name: Ensure NFS tools are installed
      ansible.builtin.package:
        name: nfs-common
        state: present

    - name: Download Kubernetes install script to the remote server
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/alex938/docker-with-kubernetes-swarm/refs/heads/main/Kubernetes/install_k8s_control.sh
        dest: /tmp/install_k8s.sh
        mode: '0755'

    - name: Execute Kubernetes install script
      ansible.builtin.shell: |
        sudo -u alex /bin/bash /tmp/install_k8s.sh
      register: install_script_result

    - name: Retrieve Kubeadm join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Show join command
      debug:
        msg: "Kubeadm join command: {{ join_command.stdout }}"
