---
- name: Install k8s and init cluster
  hosts: homelab
  become: true
  vars_files:
    - vault2.yml

  tasks:
    - name: Ensure curl is installed
      ansible.builtin.package:
        name: curl
        state: present

    - name: Download Kubernetes install script to the remote server
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/alex938/docker-with-kubernetes-swarm/refs/heads/main/Kubernetes/install_k8s.sh
        dest: /tmp/install_k8s.sh
        mode: '0755'

    - name: Execute Kubernetes install script
      ansible.builtin.shell: |
        sudo -u alex /bin/bash /tmp/install_k8s.sh
      register: install_script_result

    - name: Extract kubeadm join command
      ansible.builtin.set_fact:
        kubeadm_join_command: "{{ install_script_result.stdout | regex_search('kubeadm join.*', multiline=True) }}"

    - name: Extract discovery-token-ca-cert-hash
      ansible.builtin.set_fact:
        discovery_token_hash: "{{ install_script_result.stdout | regex_search('--discovery-token-ca-cert-hash sha256:[a-f0-9]+', multiline=True) }}"

    - name: Show kubeadm join command
      ansible.builtin.debug:
        msg: "Kubeadm join command: {{ kubeadm_join_command }}"

    - name: Show discovery token CA cert hash
      ansible.builtin.debug:
        msg: "Discovery token CA cert hash: {{ discovery_token_hash }}"
