---
- name: reboot of hosts
  hosts: homelab:k8s
  become: true
  gather_facts: false
  vars_files:
    - vault2.yml

  tasks:
    - name: Ping the host
      ansible.builtin.ping:
      register: ping_result
      ignore_unreachable: true
      ignore_errors: true

    - name: Gather facts
      ansible.builtin.setup:
      when: ping_result.ping is defined and ping_result.ping == 'pong'

    - name: immediate system reboot
      command: reboot now
      when: ping_result.ping is defined and ping_result.ping == 'pong' and ansible_distribution in ["Debian", "Ubuntu", "Kali"]
      async: 1
      poll: 0
      register: reboot_result

    - name: Debug reboot result
      debug:
        var: reboot_result