---
- name: Gather facts from servers
  hosts: servers
  gather_facts: false
  vars_files:
    - vault.yml
  
  tasks:
    - name: Ping the host
      ansible.builtin.ping:
      register: ping_result
      ignore_unreachable: true
      ignore_errors: true

    - name: Skip hosts that are unreachable
      meta: clear_host_errors
      when: ping_result is failed

    - name: Gather facts
      setup:
      when: ping_result is succeeded

    - name: Display specific fact - Operating System
      debug:
        msg: "Operating System: {{ ansible_facts['os_family'] }}"
      when: ping_result is succeeded

    - name: Display specific fact - Memory
      debug:
        msg: "Total Memory: {{ ansible_facts['memtotal_mb'] }} MB"
      when: ping_result is succeeded
