services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "192.168.2.12:53:53/tcp" #ensure IPs are mapped to host ip i.e. the ip the pihole container is running on. this fixes the gravity error
      - "192.168.2.12:53:53/udp" #ensure IPs are mapped to host ip i.e. the ip the pihole container is running on. this fixes the gravity error
      - "80:80/tcp"
    environment:
      TZ: 'Europe/London'
    volumes:
      - './pihole:/etc/pihole'
      - './dnsmasq:/etc/dnsmasq.d'
    restart: unless-stopped
