apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fileserver-ingress
  annotations:
    #nginx.ingress.kubernetes.io/use-proxy-protocol: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"  # this ensures cert-manager issues the certificate
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - software.labjunkie.org
    - omnitools.labjunkie.org
    - n8n.labjunkie.org
    - fossflow.labjunkie.org
    secretName: software-tls  # cert-manager will store the SSL certs here
  rules:
  - host: software.labjunkie.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fileserver-nginx-service
            port:
              number: 80
  - host: omnitools.labjunkie.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: omnitools
            port:
              number: 80
  - host: n8n.labjunkie.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: n8n-service
            port:
              number: 5678
  - host: fossflow.labjunkie.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fossflow-service
            port:
              number: 80
