services:
  gitlab:
    image: gitlab/gitlab-ce:17.6.4-ce.0
    container_name: gitlab
    restart: always
    hostname: 'gitlab'
    ports:
      - '2424:22'
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    shm_size: '256m'
    networks:
      - gitlab-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - '80:80'     
      - '443:443'   
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/letsencrypt
      - ./nginx_logs:/var/log/nginx
    depends_on:
      - gitlab
    networks:
      - gitlab-network

networks:
  gitlab-network:
    driver: bridge