services:
  gitlab:
    image: yrzr/gitlab-ce-arm64v8:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.labjunkie.org'
    ports:
      - '4242:22'
    volumes:
      - '/mnt/docker_volumes/gitlab/config:/etc/gitlab'
      - '/mnt/docker_volumes/gitlab/logs:/var/log/gitlab'
      - '/mnt/docker_volumes/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      - gitlab-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - '80:80'     # HTTP
      - '443:443'   # HTTPS
    volumes:
      - '/mnt/docker_volumes/gitlab/nginx.conf:/etc/nginx/nginx.conf'
      - '/mnt/docker_volumes/gitlab/certs:/etc/letsencrypt:ro'
      - '/mnt/docker_volumes/gitlab/nginx_logs:/var/log/nginx'              
    depends_on:
      - gitlab
    networks:
      - gitlab-network

networks:
  gitlab-network:
    driver: bridge