# Generated by Django 5.2.17 on 2026-08-21 09:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_commit_sha', models.CharField(blank=True, max_length=64)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('error', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='LogSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_path', models.CharField(max_length=500)),
                ('log_filename', models.CharField(max_length=300)),
                ('log_hash', models.CharField(db_index=True, max_length=64)),
                ('log_bytes', models.PositiveIntegerField(default=0)),
                ('commit_sha', models.CharField(blank=True, max_length=64)),
                ('commit_subject', models.CharField(blank=True, max_length=500)),
                ('logged_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('critical', 'Critical'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('headline', models.CharField(blank=True, max_length=500)),
                ('key_points', models.JSONField(default=list)),
                ('actions', models.JSONField(default=list)),
                ('summarised_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('summariser', models.CharField(default='claude', max_length=50)),
                ('error', models.TextField(blank=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='dashboard.service')),
            ],
            options={
                'verbose_name_plural': 'log summaries',
                'ordering': ['-summarised_at'],
                'constraints': [models.UniqueConstraint(fields=('service', 'log_hash'), name='unique_summary_per_log')],
            },
        ),
    ]
