apiVersion: v1
kind: PersistentVolume
metadata:
  name: aptcacher-volume
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume1/share1/software/aptcacher
    server: nas.batcave.local
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aptcacher-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apt-cacher-ng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aptcacher
  template:
    metadata:
      labels:
        app: aptcacher
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: apt-cacher-ng
          image: alex938/aptcachernas:nas-friendly
          ports:
            - containerPort: 3142
          volumeMounts:
            - name: aptcacher-storage
              mountPath: /var/cache/apt-cacher-ng
          readinessProbe:
            httpGet:
              path: /
              port: 3142
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: aptcacher-storage
          persistentVolumeClaim:
            claimName: aptcacher-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: aptcacher-service
spec:
  selector:
    app: aptcacher
  ports:
    - protocol: TCP
      port: 3142
      targetPort: 3142
  type: LoadBalancer
  loadBalancerIP: 192.168.2.201

