concurrent = 3
check_interval = 0
shutdown_timeout = 0

[[runners]]
  name = "shared"
  url = "https://gitlab.labjunkie.org"
  executor = "docker"

  [runners.custom_build_dir]

  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]

  [runners.docker]
    tls_verify = false
    image = "docker:24.0.5"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    shm_size = 256000000
    network_mtu = 0

    volumes = [
      "/var/run/docker.sock:/var/run/docker.sock",  
      "/cache"
    ]