apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes 5;

    events {
        worker_connections 1024;
    }

    http {
        server {
            listen 80;
            server_name localhost;

            location / {
                root /usr/share/nginx/html;
                autoindex on;
                autoindex_exact_size off;
                autoindex_localtime on;
            }
        }
    }
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: software-volume
  labels:
    type: shared
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume1/share1/software
    server: nas.batcave.local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: software-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.17.3
          ports:
            - containerPort: 80
          volumeMounts:
            - name: software-volume
              mountPath: /usr/share/nginx/html
            - name: nginx-config-volume #not really a volume, just kubernetes terminology
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: software-volume
          persistentVolumeClaim:
            claimName: software-pvc
        - name: nginx-config-volume
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30020
  selector:
    app: nginx
