---
- name: Setup ansible user on training kali
  hosts: training
  become: true
  gather_facts: true
  vars_files:
    - vault.yml
    - group_vars/training.yml

  tasks:
    - name: Ping the host
      ansible.builtin.ping:
      register: ping_result
      ignore_unreachable: true
      ignore_errors: true

    - name: Check if ansible user exists
      getent:
        database: passwd
        key: ansible
      register: ansible_user_exists
      ignore_errors: true
      when: ping_result is succeeded

    - name: Create ansible user if not present
      user:
        name: ansible
        comment: "Ansible User"
        shell: /bin/bash
        create_home: true
        state: present
      when: ansible_user_exists is failed and ping_result is succeeded
      notify: notify_ansible_user_created

    - name: Create .ssh directory for ansible user
      file:
        path: /home/ansible/.ssh
        state: directory
        owner: ansible
        group: ansible
        mode: '0700'
      notify: notify_created_ssh_dir
      when: ping_result is succeeded

    - name: Copy the existing public key to the managed nodes
      copy:
        src: "{{ ansible_pub }}"
        dest: /home/ansible/.ssh/authorized_keys
        owner: ansible
        group: ansible
        mode: '0600'
      notify: notify_copy_ansible_pub
      when: ping_result is succeeded

    - name: Ensure ansible user can use sudo without password
      lineinfile:
        path: /etc/sudoers.d/ansible
        state: present
        create: true
        line: 'ansible ALL=(ALL) NOPASSWD: ALL'
        mode: '0440'
      notify: notify_sudoers
      when: ping_result is succeeded

  handlers:
    - name: notify_ansible_user_created
      debug:
        msg: "Ansible user created on {{ hostvars[inventory_hostname]['ansible_hostname'] }}"

    - name: notify_created_ssh_dir
      debug:
        msg: "Created ansible SSH dir on {{ hostvars[inventory_hostname]['ansible_hostname'] }}"

    - name: notify_copy_ansible_pub
      debug:
        msg: "Copied ansible public key to {{ hostvars[inventory_hostname]['ansible_hostname'] }}"

    - name: notify_sudoers
      debug:
        msg: "Ansible user added to sudoers on {{ hostvars[inventory_hostname]['ansible_hostname'] }}"