---
- name: Install vscode
  hosts: training
  become: true
  vars_files:
    - vault.yml

  tasks:
    - name: Ping the host
      ping:
      register: ping_result
      ignore_unreachable: true
      ignore_errors: true

    - name: Display debug info
      debug:
        msg: "Host {{ inventory_hostname }} is running {{ ansible_distribution }}"
      when: ping_result is not failed

    - name: Add amd64 architecture
      command: dpkg --add-architecture amd64

    - name: Download VSCode .deb package to the remote host
      get_url:
        url: https://software.labjunkie.org/code_amd64.deb
        dest: /tmp/code.deb
      notify: Download vscode installer

    - name: Install VSCode from .deb package
      apt:
        deb: /tmp/code.deb
        state: present
        update_cache: yes
        cache_valid_time: 3600
      notify: Install vscode

    - name: Cleanup VSCode .deb package
      file:
        path: /tmp/code.deb
        state: absent
      notify: Cleanup vscode

  handlers:
    - name: Download vscode installer
      debug:
        msg: Download vscode installer

    - name: Install vscode
      debug:
        msg: Install vscode

    - name: Cleanup vscode
      debug:
        msg: Cleanup vscode