---
- name: Change IP address of Kali
  hosts: training
  become: true
  gather_facts: true
  vars_files:
    - vault.yml
    - group_vars/training2.yml
  #vars_prompt:
  #  - name: "new_ip"
  #    prompt: "Enter the new IP address"
  #    private: no

  pre_tasks:
    - name: Load training network gateway, dns and subnet vars
      include_vars: network_vars.yml

  tasks:
    - name: Install Networkmanager
      ansible.builtin.package:
        name: network-manager
        state: present
      when: ansible_distribution == "Kali"

    - name: Configure static IP using NetworkManager
      ansible.builtin.command: >
        nmcli connection modify "Wired connection 1"
        ipv4.addresses {{ training_subnet_ip }}/{{ SUBNET }}
        ipv4.gateway {{ DEFAULT_GATEWAY }}
        ipv4.dns {{ DNS_SERVER }}
        ipv4.method manual
      when: ansible_distribution == "Kali"

    - name: 10s wait for NetworkManager
      ansible.builtin.pause:
        seconds: 10
      when: ansible_distribution == "Kali"

    - name: Restart networkmanager
      ansible.builtin.systemd:
        name: NetworkManager
        state: restarted
      when: ansible_distribution == "Kali"

    - name: Clear old IP from the interface
      ansible.builtin.command: >
        ip addr flush dev {{ INTERFACE }}
      when: ansible_distribution == "Kali"
      async: 10
      poll: 0
      ignore_errors: yes

    - name: End playbook execution
      ansible.builtin.meta: end_play