---
- name: Setup for command box
  hosts: command_group
  become: true
  vars_files:
    - vault.yml

  vars:
    motd_debian: "*** command.training.org - no unauthorised access ***\n"
    docker_compose_file: "/opt/nexterm/docker-compose.yml"
    docker_compose_content: |
      services:
        nexterm:
          ports:
            - "6989:6989"
          restart: always
          volumes:
            - nexterm:/app/data
          image: germannewsmaker/nexterm:1.0.2-OPEN-PREVIEW
      volumes:
        nexterm:

  tasks:
    - name: Ping target host
      ping:
      register: ping_result
      ignore_unreachable: true

    - name: Fail if host is unreachable
      fail:
        msg: "The host is unreachable. Stopping playbook."
      when: ping_result is failed

    - name: Update and upgrade packages
      apt:
        update_cache: yes
        upgrade: safe

    - name: Set the MOTD
      copy:
        content: "{{ motd_debian }}"
        dest: /etc/motd
        mode: '0644'

    - name: Update resolv.conf with DNS servers
      copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 172.16.1.1

    - name: Install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: yes

    - name: Ensure qemu-guest-agent is running and enabled
      systemd:
        name: qemu-guest-agent
        state: started
        enabled: true

    - name: Install required packages
      apt:
        name:
          - sshpass
          - curl
          - vim
          - unzip
          - ansible
          - nfs-common
        state: present

    - name: Check if Docker is installed
      command: which docker
      register: docker_installed
      ignore_errors: true
      when: ping_result is not failed

    - name: Download Docker install script
      ansible.builtin.get_url:
        url: https://get.docker.com
        dest: /tmp/getdocker.sh
        mode: '0744'
      when: docker_installed.rc != 0 and ping_result is not failed

    - name: Install Docker
      shell: yes | sh /tmp/getdocker.sh
      when: docker_installed.rc != 0 and ping_result is not failed

    - name: Create directory for Docker Compose
      file:
        path: /opt/nexterm
        state: directory
        mode: '0755'

    - name: Deploy Docker Compose file
      copy:
        content: "{{ docker_compose_content }}"
        dest: "{{ docker_compose_file }}"
        mode: '0644'

    - name: Run Docker Compose to bring up services
      command: docker compose up -d
      args:
        chdir: /opt/nexterm
