---
- name: Configure sliver-svr
  hosts: servers_group
  become: true
  vars_files:
    - vault.yml

  vars:
    motd_debian: "*** sliversvr.labjunkie.org - no unauthorised access ***\n"
    sliver_service_path: "/etc/systemd/system/sliver.service"

  tasks:
    - name: Ping the host
      ping:
      register: ping_result
      ignore_unreachable: true
      ignore_errors: true

    - name: Display debug info for host
      debug:
        msg: "Host {{ inventory_hostname }} is running {{ ansible_distribution }} {{ ansible_distribution_version }}"
      when: ping_result is not failed

    - name: Set SSH MOTD
      copy:
        content: "{{ motd_debian }}"
        dest: /etc/motd
        mode: '0644'
      when: ping_result is not failed

    - name: Update resolv.conf with DNS servers
      copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 172.16.1.1
      when: ping_result is not failed

    - name: configure apt proxy
      copy:
        dest: /etc/apt/apt.conf.d/01proxy
        content: |
          Acquire::http::Proxy "http://apt.labjunkie.org:3142";
          Acquire::https::download.docker.com::Proxy "DIRECT";
        owner: root
        group: root
        mode: '0644'
      when: ping_result is not failed

    - name: Download and execute Kali setup script
      shell: |
        wget -qO- https://software.labjunkie.org/scripts/kali_setup.sh | sudo bash | tee /var/log/kali_setup.log
      no_log: false
      ignore_errors: true

    - name: wait 10
      wait_for:
        timeout: 10

    - name: Download Sliver server binary
      get_url:
        url: https://software.labjunkie.org/sliver/sliver-server
        dest: /usr/local/bin/sliver-server
        mode: '0755'

    - name: Download Sliver client binary
      get_url:
        url: https://software.labjunkie.org/sliver/sliver-client
        dest: /usr/local/bin/sliver
        mode: '0755'

    - name: ensure /home/kali/.sliver-client directory exists
      file:
        path: /home/kali/.sliver-client
        state: directory
        owner: kali
        group: kali
        mode: '0755'
      when: ping_result is not failed

    - name: download Sliver Armory archive
      get_url:
        url: https://software.labjunkie.org/sliver-armory.tar.gz
        dest: /tmp/sliver-armory.tar.gz
        mode: '0644'
      when: ping_result is not failed

    - name: extract Sliver Armory archive to /home/kali/.sliver-client/
      unarchive:
        src: /tmp/sliver-armory.tar.gz
        dest: /home/kali/.sliver-client/
        remote_src: yes
        owner: kali
        group: kali
      when: ping_result is not failed

    - name: Create systemd service for Sliver
      copy:
        dest: "{{ sliver_service_path }}"
        content: |
          [Unit]
          Description=Sliver
          After=network.target
          StartLimitIntervalSec=0

          [Service]
          Type=simple
          Restart=on-failure
          RestartSec=3
          User=root
          ExecStart=/usr/local/bin/sliver-server daemon

          [Install]
          WantedBy=multi-user.target
        mode: '0600'

    - name: Unpack sliver-server
      shell: |
        sliver-server unpack --force >> /var/log/kali_setup.log 2>&1
      no_log: false
      ignore_errors: true

    - name: Activate sliver multiplayer mode
      shell: |
        bash -c 'sliver-server <<< "multiplayer"' >> /var/log/kali_setup.log 2>&1 
      async: 10
      poll: 0
      ignore_errors: true

    - name: Reload systemd to apply Sliver service
      systemd:
        daemon_reload: yes

    - name: Enable Sliver service at startup
      systemd:
        name: sliver
        enabled: yes

    - name: Start Sliver service
      systemd:
        name: sliver
        state: started

    - name: download chisel binary
      get_url:
        url: https://software.labjunkie.org/chisel_1.10.1_linux_amd64.gz
        dest: /tmp/chisel.gz
        mode: '0644'
      when: ping_result is not failed

    - name: decompress chisel binary
      command: gunzip -f /tmp/chisel.gz
      when: ping_result is not failed

    - name: move chisel binary to /usr/local/bin
      copy:
        src: /tmp/chisel
        dest: /usr/local/bin/chisel
        remote_src: yes
        owner: root
        group: root
        mode: '0755'
      when: ping_result is not failed

    - name: ensure /home/kali/Desktop exists
      file:
        path: /home/kali/Desktop
        state: directory
        owner: kali
        group: kali
        mode: '0755'
      when: ping_result is not failed

    - name: create .desktop shortcuts
      copy:
        dest: "/home/kali/Desktop/{{ item.filename }}"
        content: |
          [Desktop Entry]
          Version=1.0
          Type=Application
          Name={{ item.name }}
          Comment={{ item.comment }}
          Exec=xdg-open {{ item.url }}
          Icon=internet-web-browser
          Terminal=false
          StartupNotify=true
        owner: kali
        group: kali
        mode: '0755'
      loop:
        - { name: "target", comment: "target", url: "http://poe.local", filename: "poe.desktop" }
        - { name: "share", comment: "share", url: "http://172.16.1.10:3000", filename: "share.desktop" }
        - { name: "software", comment: "software", url: "https://software.labjunkie.org", filename: "software.desktop" }
        - { name: "rules", comment: "rules", url: "https://software.labjunkie.org/rules.html", filename: "rules.desktop" }

