---
- name: Configure cloud-init Kali Linux
  hosts: training
  become: true
  vars_files:
    - vault.yml

  vars:
    motd_debian: "*** training kali - no unauthorised access ***\n"

  tasks:
    - name: Ping the host
      ping:
      register: ping_result
      ignore_unreachable: true
      ignore_errors: true

    - name: Display debug info for host
      debug:
        msg: "Host {{ inventory_hostname }} is running {{ ansible_distribution }} {{ ansible_distribution_version }}"
      when: ping_result is not failed

    - name: Set SSH MOTD
      copy:
        content: "{{ motd_debian }}"
        dest: /etc/motd
        mode: '0644'
      when: ping_result is not failed

    - name: Preconfigure language and keyboard settings
      shell: |
        echo "keyboard-configuration keyboard-configuration/layoutcode string gb" | debconf-set-selections
        echo "keyboard-configuration keyboard-configuration/modelcode string pc105" | debconf-set-selections
        echo "keyboard-configuration keyboard-configuration/layout select United Kingdom" | debconf-set-selections
        echo "keyboard-configuration keyboard-configuration/variant select English (UK)" | debconf-set-selections
        echo "locales locales/default_environment_locale select en_GB.UTF-8" | debconf-set-selections
        echo "locales locales/locales_to_be_generated multiselect en_GB.UTF-8 UTF-8" | debconf-set-selections
      when: ping_result is not failed

    - name: Update resolv.conf with DNS servers
      copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 172.16.1.1
      when: ping_result is not failed

    - name: Download and execute Kali setup script
      shell: |
        wget -qO- https://software.labjunkie.org/scripts/kali_setup.sh | sudo bash | tee /var/log/kali_setup.log
      no_log: false
      ignore_errors: true
      async: 0
      poll: 0