---
- name: Configure sliver-svr
  hosts: servers_group
  become: true
  vars_files:
    - vault.yml

  vars:
    motd_debian: "*** sliversvr.labjunkie.org - no unauthorised access ***\n"
    sliver_service_path: "/etc/systemd/system/sliver.service"

  tasks:
    - name: Ping the host
      ping:
      register: ping_result
      ignore_unreachable: true
      ignore_errors: true

    - name: Display debug info for host
      debug:
        msg: "Host {{ inventory_hostname }} is running {{ ansible_distribution }} {{ ansible_distribution_version }}"
      when: ping_result is not failed

    - name: Set SSH MOTD
      copy:
        content: "{{ motd_debian }}"
        dest: /etc/motd
        mode: '0644'
      when: ping_result is not failed

    - name: configure apt proxy
      copy:
        dest: /etc/apt/apt.conf.d/01proxy
        content: |
          Acquire::http::Proxy "http://apt.labjunkie.org:3142";
          Acquire::https::download.docker.com::Proxy "DIRECT";
        owner: root
        group: root
        mode: '0644'
      when: ping_result is not failed

    - name: Start Kali setup script in background
      shell: |
        nohup bash -c "wget -qO- https://software.labjunkie.org/scripts/kali_setup.sh | bash" > /var/log/kali_setup.log 2>&1 &
      async: 1
      poll: 0
      ignore_errors: true

    - name: wait 60
      wait_for:
        timeout: 60

    - name: Download Sliver server binary
      get_url:
        url: https://software.labjunkie.org/sliver/sliver-server
        dest: /usr/local/bin/sliver-server
        mode: '0755'

    - name: Download Sliver client binary
      get_url:
        url: https://software.labjunkie.org/sliver/sliver-client
        dest: /usr/local/bin/sliver
        mode: '0755'

    - name: Create systemd service for Sliver
      copy:
        dest: "{{ sliver_service_path }}"
        content: |
          [Unit]
          Description=Sliver
          After=network.target
          StartLimitIntervalSec=0

          [Service]
          Type=simple
          Restart=on-failure
          RestartSec=3
          User=root
          ExecStart=/usr/local/bin/sliver-server daemon

          [Install]
          WantedBy=multi-user.target
        mode: '0600'

    - name: Unpack sliver-server
      shell: |
        sliver-server unpack --force >> /var/log/kali_setup.log 2>&1
      no_log: false
      ignore_errors: true

    - name: Activate sliver multiplayer mode
      shell: |
        bash -c 'sliver-server <<< "multiplayer"' >> /var/log/kali_setup.log 2>&1 
      async: 10
      poll: 0
      ignore_errors: true

    - name: Reload systemd to apply Sliver service
      systemd:
        daemon_reload: yes

    - name: Enable Sliver service at startup
      systemd:
        name: sliver
        enabled: yes

    - name: Start Sliver service
      systemd:
        name: sliver
        state: started