---
- name: Base setup of new training kali
  hosts: training
  become: true
  vars_files:
    - vault.yml
    - group_vars/training2.yml
  vars:
    motd_debian: "*** training kali - no unauthorised access ***\n"

  tasks:
    - name: Ping the host
      ping:
      register: ping_result
      ignore_unreachable: true
      ignore_errors: true

    - name: Display debug info for host
      debug:
        msg: "Host {{ inventory_hostname }} is running {{ ansible_distribution }}"
      when: ping_result is not failed

    - name: set ssh motd
      copy:
        content: "{{ motd_debian }}"
        dest: /etc/motd
        mode: '0644'
      when: ping_result is not failed
      notify: MOTD changed

    - name: Update package cache
      apt:
        update_cache: yes
        force_apt_get: yes
      when: ansible_distribution in ["Debian", "Ubuntu", "Kali"] and ping_result is not failed
      notify: Updated Server

    - name: install sliver package
      apt:
        name: sliver
        state: present
      when: ansible_distribution in ["Debian", "Ubuntu", "Kali"] and ping_result is not failed
      notify: Sliver Installed

    - name: install xrdp package
      apt:
        name: xrdp
        state: present
      when: ansible_distribution in ["Debian", "Ubuntu", "Kali"] and ping_result is not failed
      notify: XRDP Installed

    - name: enable XRDP service on startup
      systemd:
        name: xrdp
        enabled: yes
        state: started
      when: ansible_distribution in ["Debian", "Ubuntu", "Kali"] and ping_result is not failed
      notify: XRDP Enabled on Startup

    - name: enabled session manager service on startup
      systemd:
        name: xrdp-sesman
        enabled: yes
        state: started
      when: ansible_distribution in ["Debian", "Ubuntu", "Kali"] and ping_result is not failed
      notify: Sesman Enabled on Startup

    - name: copy vscode .deb package to host
      copy:
        src: ../../playbook_files/code.deb
        dest: /tmp/code.deb
      notify: Copy vscode installer

    - name: install vscode
      apt:
        deb: /tmp/code.deb
        state: present
      notify: Install vscode

    - name: cleanup vscode .deb
      file:
        path: /tmp/code.deb
        state: absent
      notify: Cleanup vscode

    - name: copy vscode cpp extension
      copy:
        src: ../../playbook_files/ms-vscode.cpptools-1.21.6@linux-x64.vsix
        dest: /tmp/ms-vscode.cpptools-1.21.6@linux-x64.vsix
      notify: Copy cpp extension

    - name: create VS Code extensions directory if not exists
      file:
        path: /home/kali/.vscode/extensions
        state: directory
        mode: '0755'
        owner: kali
        group: kali

    - name: unzip the VSIX extension into the extensions directory
      unarchive:
        src: /tmp/ms-vscode.cpptools-1.21.6@linux-x64.vsix
        dest: /home/kali/.vscode/extensions/
        remote_src: yes

    - name: clean up extension files
      file:
        path: /tmp/cms-vscode.cpptools-1.21.6@linux-x64.vsix
        state: absent
      notify: Cleanup up cpp extension files

  handlers:
    - name: MOTD changed
      debug:
        msg: The MOTD was changed on {{ inventory_hostname }}

    - name: Updated Server
      debug:
        msg: Packages were updated

    - name: Sliver Installed
      debug:
        msg: Sliver Installed

    - name: XRDP Installed
      debug:
        msg: XRDP Installed

    - name: XRDP Enabled on Startup
      debug:
        msg: XRDP Enabled on Startup

    - name: Sesman Enabled on Startup
      debug:
        msg: Sesman Enabled on Startup

    - name: Copy vscode installer
      debug:
        msg: Copy vscode installer

    - name: Install vscode
      debug:
        msg: Install vscode

    - name: Cleanup vscode
      debug:
        msg: Cleanup vscode

    - name: Copy cpp extension
      debug:
        msg: Copy cpp extension

    - name: Install cpp extension
      debug:
        msg: Install cpp extension

    - name: Cleanup up cpp extension files
      debug:
        msg: Cleanup up cpp extension files