name: Ansible Playbook Check

on:
  push:
    branches:
      - main
    paths:
      - '**/*.yml'  
  pull_request:
    branches:
      - main
    paths:
      - '**/*.yml'  
  workflow_dispatch:

jobs:
  lint-and-check:
    name: Lint and Syntax Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible and Linters
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint yamllint

      - name: Find modified playbooks
        id: changed-files
        run: |
          echo "PLAYBOOKS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.yml$' || true)" >> $GITHUB_ENV

      - name: Lint and Check Ansible Playbooks
        if: env.PLAYBOOKS != ''
        run: |
          for playbook in $PLAYBOOKS; do
            echo "Processing $playbook"
            yamllint "$playbook"
            ansible-lint "$playbook"
            ansible-playbook -i localhost, "$playbook" --syntax-check
          done
