name: Ansible Playbook Syntax Check

on:
  push:
    branches:
      - main
    paths:
      - 'playbooks/**/*.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'playbooks/**/*.yml'
  workflow_dispatch:

jobs:
  syntax-check:
    name: Ansible Syntax Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python & Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Detect changed playbooks
        id: changed-files
        run: |
          git fetch --no-tags --depth=2 origin main  # Ensure we have the previous commit

          # Detect changed files in the last commit
          PLAYBOOKS=$(git diff --name-only HEAD^ HEAD | grep -E '^playbooks/((?!group_vars|host_vars).)*\.yml$' || true)

          # If no changes detected, fall back to staged files (for manual workflow_dispatch)
          if [ -z "$PLAYBOOKS" ]; then
            echo "No changes detected with git diff. Checking unstaged files..."
            PLAYBOOKS=$(git ls-files --modified --others --exclude-standard | grep '^playbooks/.*\.yml$' || true)
          fi

          # Store playbooks in a space-separated format for GitHub Actions
          echo "PLAYBOOKS=$(echo "$PLAYBOOKS" | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Run Ansible Syntax Check
        if: ${{ env.PLAYBOOKS != '' }}
        run: |
          echo "Running syntax check on changed playbooks: $PLAYBOOKS"

          # Run syntax check for each changed file
          for playbook in $PLAYBOOKS; do
            echo "Checking syntax for $playbook"
            ansible-playbook -i localhost, "$playbook" --syntax-check || exit 1
          done
