name: Ansible Playbook Syntax Check

on:
  push:
    branches:
      - main
    paths:
      - 'playbooks/**/*.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'playbooks/**/*.yml'
  workflow_dispatch:

jobs:
  syntax-check:
    name: Ansible Syntax Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python & Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Detect changed playbooks
        id: changed-files
        run: |
          PLAYBOOKS=$(git diff --name-only --diff-filter=AM origin/main | grep '^playbooks/.*\.yml$' || true)
          echo "Changed playbooks: $PLAYBOOKS"
          echo "PLAYBOOKS=$PLAYBOOKS" >> $GITHUB_ENV

      - name: Run Ansible Syntax Check
        if: ${{ env.PLAYBOOKS != '' }}
        run: |
          for playbook in $PLAYBOOKS; do
            echo "Checking syntax for $playbook"
            ansible-playbook -i localhost, "$playbook" --syntax-check || exit 1
          done
