services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81' #admin webui
    volumes:
      - ./data:/data
      - ./certs:/etc/letsencrypt
    networks:
      - shared_network

networks:
  shared_network:
    external: true